config/routes.rb
OpenData::Application.routes.draw do

  match "data/establecimientos_escolares_priorizados_elegibles_fonacide" => 'requerimientos_infraestructuras#catalogo', :as => :data_requerimientos_infraestructuras_catalogo

  match 'app/academia/inventario_bienes_muebles' => 'visualizaciones#academia_inventario_bienes_muebles', :as => :app_academia_inventario_bienes_muebles
  match 'app/academia/inventario_bienes_inmuebles' => 'visualizaciones#academia_inventario_bienes_inmuebles', :as => :app_academia_inventario_bienes_inmuebles
  match 'app/academia/inventario_bienes_rodados' => 'visualizaciones#academia_inventario_bienes_rodados', :as => :app_academia_inventario_bienes_rodados
  match 'app/academia/funcionarios_administrativos' => 'visualizaciones#academia_funcionarios_administrativos', :as => :app_academia_funcionarios_administrativos
  match 'app/academia/funcionarios_docentes' => 'visualizaciones#academia_funcionarios_docentes', :as => :app_academia_funcionarios_docentes
  match "data/visualizaciones" => 'visualizaciones#index', :as => :data_visualizaciones
  
  match "data/registros_titulos_lista" => 'registros_titulos#lista', :as => :data_registros_titulos_lista
  match 'data/registros_titulos' => 'registros_titulos#index', :as => :data_registros_titulos
  match 'def/registros_titulos' => 'registros_titulos#diccionario', :as => :def_registros_titulos

  match 'app/mapa_matriculaciones' => 'mapa_matriculaciones#index', :as => :app_mapa_matriculaciones

  match "data/contrataciones_lista" => 'contrataciones#lista', :as => :data_contrataciones_lista
  match 'data/contrataciones' => 'contrataciones#index', :as => :data_contrataciones
  match 'def/contrataciones' => 'contrataciones#diccionario', :as => :def_contrataciones

  match "id/nomina_administrativos/:codigo_trabajador" => "nominas#administrativo_doc", :as => :id_nomimas_administrativo
  match "doc/nomina_administrativos/:codigo_trabajador" =>"nominas#administrativo_doc", :as => :doc_nomimas_administrativo
  match "data/nomina_administrativos_detalles" => 'nominas#detalles', :as => :data_nomina_administrativos_detalles
  match "data/nomina_administrativos_lista" => 'nominas#lista', :as => :data_nomina_administrativos_lista
  match 'data/nomina_administrativos' => 'nominas#index', :as => :data_nomina_administrativos
  match 'def/nomina_administrativos' => 'nominas#diccionario', :as => :def_nomina_administrativos
  match "id/nomina_docentes/:codigo_trabajador" => "nominas#docentes_doc", :as => :id_nomimas_docentes
  match "doc/nomina_docentes/:codigo_trabajador" =>"nominas#docentes_doc", :as => :doc_nomimas_docentes
  match "data/nomina_docentes_detalles" => 'nominas#docentes_detalles', :as => :data_nomina_docentes_detalles
  match "data/nomina_docentes_lista" => 'nominas#docentes_lista', :as => :data_nomina_docentes_lista
  match 'data/nomina_docentes' => 'nominas#docentes', :as => :data_nomina_docentes
  match 'def/nomina_docentes' => 'nominas#docentes_diccionario', :as => :def_nomina_docentes

  match "data/matriculaciones_educacion_permanente_lista" => 'matriculaciones_educacion_permanente#lista', :as => :data_matriculaciones_educacion_permanente_lista
  match 'data/matriculaciones_educacion_permanente' => 'matriculaciones_educacion_permanente#index', :as => :data_matriculaciones_educacion_permanente
  match 'def/matriculaciones_educacion_permanente' => 'matriculaciones_educacion_permanente#diccionario', :as => :def_matriculaciones_educacion_permanente

  match "data/matriculaciones_educacion_inclusiva_lista" => 'matriculaciones_educacion_inclusiva#lista', :as => :data_matriculaciones_educacion_inclusiva_lista
  match 'data/matriculaciones_educacion_inclusiva' => 'matriculaciones_educacion_inclusiva#index', :as => :data_matriculaciones_educacion_inclusiva
  match 'def/matriculaciones_educacion_inclusiva' => 'matriculaciones_educacion_inclusiva#diccionario', :as => :def_matriculaciones_educacion_inclusiva

  match "data/matriculaciones_media_lista" => 'matriculaciones_media#lista', :as => :data_matriculaciones_media_lista
  match 'data/matriculaciones_media' => 'matriculaciones_media#index', :as => :data_matriculaciones_media
  match 'def/matriculaciones_media' => 'matriculaciones_media#diccionario', :as => :def_matriculaciones_media

  match "data/matriculaciones_inicial_lista" => 'matriculaciones_inicial#lista', :as => :data_matriculaciones_inicial_lista
  match 'data/matriculaciones_inicial' => 'matriculaciones_inicial#index', :as => :data_matriculaciones_inicial
  match 'def/matriculaciones_inicial' => 'matriculaciones_inicial#diccionario', :as => :def_matriculaciones_inicial

  match "data/matriculaciones_educacion_escolar_basica_lista" => 'matriculaciones_educacion_escolar_basica#lista', :as => :data_matriculaciones_educacion_escolar_basica_lista
  match 'data/matriculaciones_educacion_escolar_basica' => 'matriculaciones_educacion_escolar_basica#index', :as => :data_matriculaciones_educacion_escolar_basica
  match 'def/matriculaciones_educacion_escolar_basica' => 'matriculaciones_educacion_escolar_basica#diccionario', :as => :def_matriculaciones_educacion_escolar_basica

  match "data/matriculaciones_departamentos_distritos_lista" => 'matriculaciones_departamentos_distritos#lista', :as => :data_matriculaciones_departamentos_distritos_lista
  match 'data/matriculaciones_departamentos_distritos' => 'matriculaciones_departamentos_distritos#index', :as => :data_matriculaciones_departamentos_distritos
  match 'def/matriculaciones_departamentos_distritos' => 'matriculaciones_departamentos_distritos#diccionario', :as => :def_matriculaciones_departamentos_distritos

  match "data/matriculaciones_educacion_media_lista" => 'matriculaciones_educacion_media#lista', :as => :data_matriculaciones_educacion_media_lista
  match 'data/matriculaciones_educacion_media' => 'matriculaciones_educacion_media#index', :as => :data_matriculaciones_educacion_media
  match 'def/matriculaciones_educacion_media' => 'matriculaciones_educacion_media#diccionario', :as => :def_matriculaciones_educacion_media
  
  match "data/matriculaciones_educacion_superior_lista" => 'matriculaciones_educacion_superior#lista', :as => :data_matriculaciones_educacion_superior_lista
  match 'data/matriculaciones_educacion_superior' => 'matriculaciones_educacion_superior#index', :as => :data_matriculaciones_educacion_superior
  match 'def/matriculaciones_educacion_superior' => 'matriculaciones_educacion_superior#diccionario', :as => :def_matriculaciones_educacion_superior

  match "id/instituciones/:codigo_institucion" => "instituciones#doc", :as => :id_instituciones
  match "doc/instituciones/:codigo_institucion" => "instituciones#doc", :as => :doc_instituciones
  match "data/instituciones_lista" => 'instituciones#lista', :as => :data_instituciones_lista
  match 'data/instituciones' => 'instituciones#index', :as => :data_instituciones
  match 'def/instituciones' => 'instituciones#diccionario', :as => :def_instituciones
  
=begin
  match "id/directorios_instituciones/:codigo_institucion" => "directorios_instituciones#doc", :as => :id_instituciones
  match "doc/directorios_instituciones/:codigo_institucion" => "directorios_instituciones#doc", :as => :doc_directorios_instituciones
=end
  match "data/directorios_instituciones_lista" => 'directorios_instituciones#lista', :as => :data_directorios_instituciones_lista
  match 'data/directorios_instituciones' => 'directorios_instituciones#index', :as => :data_directorios_instituciones
  match 'def/directorios_instituciones' => 'directorios_instituciones#diccionario', :as => :def_directorios_instituciones
  
  match "data/requerimientos_aulas_lista" => 'requerimientos_aulas#lista', :as => :data_requerimientos_aulas_lista
  match 'data/requerimientos_aulas' => 'requerimientos_aulas#index', :as => :data_requerimientos_aulas
  match 'def/requerimientos_aulas' => 'requerimientos_aulas#diccionario', :as => :def_requerimientos_aulas
  
  match "data/requerimientos_sanitarios_lista" => 'requerimientos_sanitarios#lista', :as => :data_requerimientos_sanitarios_lista
  match 'data/requerimientos_sanitarios' => 'requerimientos_sanitarios#index', :as => :data_requerimientos_sanitarios
  match 'def/requerimientos_sanitarios' => 'requerimientos_sanitarios#diccionario', :as => :def_requerimientos_sanitarios
  
  match "data/requerimientos_mobiliarios_lista" => 'requerimientos_mobiliarios#lista', :as => :data_requerimientos_mobiliarios_lista
  match 'data/requerimientos_mobiliarios' => 'requerimientos_mobiliarios#index', :as => :data_requerimientos_mobiliarios
  match 'def/requerimientos_mobiliarios' => 'requerimientos_mobiliarios#diccionario', :as => :def_requerimientos_mobiliarios
  
  match "data/requerimientos_otros_espacios_lista" => 'requerimientos_otros_espacios#lista', :as => :data_requerimientos_otros_espacios_lista
  match 'data/requerimientos_otros_espacios' => 'requerimientos_otros_espacios#index', :as => :data_requerimientos_otros_espacios
  match 'def/requerimientos_otros_espacios' => 'requerimientos_otros_espacios#diccionario', :as => :def_requerimientos_otros_espacios
  
  match "data/requerimientos_alimentacion_lista" => 'requerimientos_alimentacion#lista', :as => :data_requerimientos_alimentacion_lista
  match 'data/requerimientos_alimentacion' => 'requerimientos_alimentacion#index', :as => :data_requerimientos_alimentacion
  match 'def/requerimientos_alimentacion' => 'requerimientos_alimentacion#diccionario', :as => :def_requerimientos_alimentacion
  
  match "data/servicios_basicos_lista" => 'servicios_basicos#lista', :as => :data_servicios_basicos_lista
  match 'data/servicios_basicos' => 'servicios_basicos#index', :as => :data_servicios_basicos
  match 'def/servicios_basicos' => 'servicios_basicos#diccionario', :as => :def_servicios_basicos

  match "id/establecimientos/:codigo_establecimiento" => "data#establecimientos_doc", :as => :id_establecimientos

app/controllers/visualizaciones_controller.rb
# -*- encoding : utf-8 -*-
class VisualizacionesController < ApplicationController
  
  before_filter :redireccionar_uri

  def index
    
  end

  def academia_funcionarios_docentes

  end

  def academia_funcionarios_administrativos

  end

  def academia_inventario_bienes_rodados

  end

  def academia_inventario_bienes_inmuebles

  end

  def academia_inventario_bienes_muebles

    respond_to do |f|

      f.html {render :layout => 'application_wide'}

    end

  end

end

app/views/visualizaciones/academia_funcionarios_administrativos.html.erb
<div class="container">
  <div class="row ">
    <div class="col-md-12">
      <h2 style="border-bottom: 2px solid gray;">
        Funcionarios Administrativos
        <span style="float:right;">
          <%= link_to "Visualizaciones", mec_custom_url(data_visualizaciones_url), :title => "Ir a Visualizaciones", :style => "font-size:12px;" unless params[:embedded]%>
          <%= link_to image_tag("noticias.png", :style => "width:24px;"), mec_custom_url(data_visualizaciones_url), :title => "Ir a Visualizaciones" unless params[:embedded]%>
          <%= link_to "Inicio", mec_custom_url(index_url), :title => "Ir al inicio", :style => "font-size:12px;" unless params[:embedded]%>
          <%= link_to image_tag("home.png", :style => "width:24px;"), mec_custom_url(index_url), :title => "Ir al inicio" unless params[:embedded]%>
        </span>
      </h2> 
      <div style="clear:both;"></div> 
      <div class="map-container">
      <p>Esta visualización fue desarrollada por <a href="http://opendata.pol.una.py/?p=88" target="_blank">alumnos de Ingeniería Informática de la Facultad Politécnica de la Universidad Nacional de Asunción</a>.</p>

       <script id="infogram_0_verena91_1414754013" src="//e.infogr.am/js/embed.js" type="text/javascript"></script><div style="width:100%;border-top:1px solid #acacac;padding-top:3px;font-family:Arial;font-size:10px;text-align:center;"><a target="_blank" href="//infogr.am/verena91_1414754013" style="color:#acacac;text-decoration:none;">Gastos por concepto: junio, julio y agosto 2014.</a> | <a style="color:#acacac;text-decoration:none;" href="//infogr.am" target="_blank">Create Infographics</a></div>

       <p style="text-align: left; margin-top: 20px;">La aplicación desarrollada se encuentra disponible en el siguiente enlace:&nbsp;<a title="http://opendata.pol.una.py/electiva6/" href="http://opendata.pol.una.py/electiva6/"><strong>http://opendata.pol.una.py/electiva6/</strong></a></p>

       <p style="text-align: left;"><strong>Autores: </strong></p>
       <ul>
        <li style="text-align: left;">Camilo Báez</li>
        <li style="text-align: left;">Verena Ojeda</li>
        <li style="text-align: left;">Joan Ruax</li>
        <li style="text-align: left;">Natalia Valdez</li>
       </ul>

      </div><!--/span-->
    
    </div>
  
  </div><!--/row-->

</div><!--/.container-->

app/views/visualizaciones/academia_funcionarios_docentes.html.erb
<div class="container">
  <div class="row ">
    <div class="col-md-12">
      <h2 style="border-bottom: 2px solid gray;">
        Funcionarios Docentes
        <span style="float:right;">
          <%= link_to "Visualizaciones", mec_custom_url(data_visualizaciones_url), :title => "Ir a Visualizaciones", :style => "font-size:12px;" unless params[:embedded]%>
          <%= link_to image_tag("noticias.png", :style => "width:24px;"), mec_custom_url(data_visualizaciones_url), :title => "Ir a Visualizaciones" unless params[:embedded]%>
          <%= link_to "Inicio", mec_custom_url(index_url), :title => "Ir al inicio", :style => "font-size:12px;" unless params[:embedded]%>
          <%= link_to image_tag("home.png", :style => "width:24px;"), mec_custom_url(index_url), :title => "Ir al inicio" unless params[:embedded]%>
        </span>
      </h2> 
      <div style="clear:both;"></div> 
      <div class="map-container">
      <p>Esta visualización fue desarrollada por <a href="http://opendata.pol.una.py/?p=75" target="_blank">alumnos de Ingeniería Informática de la Facultad Politécnica de la Universidad Nacional de Asunción</a>.</p>
       <script id="infogram_0_objeto_gas-038698" src="//e.infogr.am/js/embed.js" type="text/javascript"></script><div style="width:100%;border-top:1px solid #acacac;padding-top:3px;font-family:Arial;font-size:10px;text-align:center;"><a style="color:#acacac;text-decoration:none;" href="//infogr.am" target="_blank">Create Infographics</a></div>
        
        <p style="text-align: left;"><strong>Autores: </strong></p>
       <ul>
        <li>Pablo López</li>
        <li>Julio Reyes</li>
        <li>Rodrigo Valdez</li>
        <li>Diego Ramírez</li>
      </ul>

      </div><!--/span-->
    
    </div>
  
  </div><!--/row-->

</div><!--/.container-->

app/views/visualizaciones/academia_inventario_bienes_inmuebles.html.erb
<div class="container">
  <div class="row ">
    <div class="col-md-12">
      <h2 style="border-bottom: 2px solid gray;">
        Inventario de Bienes - Inmuebles
        <span style="float:right;">
          <%= link_to "Visualizaciones", mec_custom_url(data_visualizaciones_url), :title => "Ir a Visualizaciones", :style => "font-size:12px;" unless params[:embedded]%>
          <%= link_to image_tag("noticias.png", :style => "width:24px;"), mec_custom_url(data_visualizaciones_url), :title => "Ir a Visualizaciones" unless params[:embedded]%>
          <%= link_to "Inicio", mec_custom_url(index_url), :title => "Ir al inicio", :style => "font-size:12px;" unless params[:embedded]%>
          <%= link_to image_tag("home.png", :style => "width:24px;"), mec_custom_url(index_url), :title => "Ir al inicio" unless params[:embedded]%>
        </span>
      </h2> 
      <div style="clear:both;"></div> 
      <div class="map-container">
      <p>Esta visualización fue desarrollada por <a href="http://opendata.pol.una.py/?p=191" target="_blank">alumnos de Ingeniería Informática de la Facultad Politécnica de la Universidad Nacional de Asunción</a>.</p>

      <script src="https://public.tableausoftware.com/javascripts/api/viz_v1.js" type="text/javascript"></script>
      <h4 style="border-bottom:2px solid gray;">Inmuebles por superficie.</h4>

      <div class="tableauPlaceholder" style="width: 100%; height: 458px;"><noscript><a href='#'><img alt='Sheet 1 ' src='https://public.tableausoftware.com/static/images/In/InmueblesPorTamao/Sheet1/1_rss.png' style='border: none' /></a></noscript><object class="tableauViz" style="display: none;" width="100%" height="458"><param name="host_url" value="https%3A%2F%2Fpublic.tableausoftware.com%2F" /><param name="site_root" value="" /><param name="name" value="InmueblesPorTamao/Sheet1" /><param name="tabs" value="no" /><param name="toolbar" value="yes" /><param name="static_image" value="https://public.tableausoftware.com/static/images/In/InmueblesPorTamao/Sheet1/1.png" /><param name="animate_transition" value="yes" /><param name="display_static_image" value="yes" /><param name="display_spinner" value="yes" /><param name="display_overlay" value="yes" /><param name="display_count" value="yes" /></object></div>

      <h4 style="border-bottom:2px solid gray;">Inmuebles por departamento.</h4>
      <iframe width="100%" height="150" src="http://bl.ocks.org/sgip/raw/1844cfeca7e02d2cd9d7" style="min-height: 1200px;border:none;"></iframe>


    </div>
  
  </div><!--/row-->

</div><!--/.container-->

app/views/visualizaciones/index.html.erb
  <center><h1>Datos Abiertos del Ministerio de Educación y Cultura</h1><%= image_tag "datos-abiertos-nuevo.png", :style => "width:320px;" %></center>
  <div class="container">
    <div class="row">
          
      <div class="menu-tab">
        <div><%= link_to "Datasets", mec_custom_url(index_url) %></div>
        <div style="background:silver;"><%= link_to "Visualizaciones".html_safe, mec_custom_url(data_visualizaciones_url) %></div>
      </div>
      <div style="clear:both;"></div>

      <!-- Page Heading -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Visualizaciones del MEC
                    </br>
                    <small>Desarrolladas por nuestro equipo técnico</small>
                </h1>
            </div>
        </div>
        <!-- /.row -->

        <!-- Project One -->
        <div class="row">
            <div class="col-md-7">
              <!--
              <a href="http://datos.mec.gov.py/app/mapa_matriculaciones">
                  <%#= image_tag "viz/mapa_matriculados.png", class: 'img-responsive'%>
                </a>
              -->
                <%= link_to image_tag('viz/mapa_matriculados.png', class: 'img-responsive'), mec_custom_url(app_mapa_matriculaciones_url) %>
            </div>
            <div class="col-md-5">
                <h3>Mapa de Matriculaciones</h3>
                <h4>Al año 2012</h4>
                <p></p>
                <%= link_to "Ir a la visualizaci&oacute;n<span class='glyphicon glyphicon-chevron-right'></span>".html_safe, mec_custom_url(app_mapa_matriculaciones_url), class: 'btn btn-primary' %>
                <!--
                  <a class="btn btn-primary" href="http://datos.mec.gov.py/app/mapa_matriculaciones">Ir a la visualización<span class="glyphicon glyphicon-chevron-right"></span></a>
                -->
            </div>
        </div>
        <!-- /.row -->

        <!-- Page Heading -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Visualizaciones de la Comunidad
                    </br>
                    <small>Desarrolladas por la Academia</small>
                </h1>
            </div>
        </div>

        <!-- Project Two -->
        <div class="row">
          <div class="col-md-7">
                <!--
                <a href="http://opendata.pol.una.py/?p=75#visualizacion" target="_blank">
                  <%#= image_tag "viz/docentes.png", class: 'img-responsive'%>
                </a>
                -->
                <%= link_to image_tag('viz/docentes.png', class: 'img-responsive'), mec_custom_url(app_academia_funcionarios_docentes_url) %>
            </div>
            <div class="col-md-5">
                <h3>Funcionarios Docentes</h3>
                <h4>Del MEC</h4>
                <p>Ver el <a href="http://opendata.pol.una.py/?p=75" target="_blank">blog</a>.</p>
                <%= link_to "Ir a la visualizaci&oacute;n<span class='glyphicon glyphicon-chevron-right'></span>".html_safe, mec_custom_url(app_academia_funcionarios_docentes_url), class: 'btn btn-primary' %>
                <!--
                <a class="btn btn-primary" href="http://opendata.pol.una.py/?p=75#visualizacion" target="_blank">Ir a la visualización<span class="glyphicon glyphicon-chevron-right"></span></a>
                -->
            </div>
        </div>
        <!-- /.row -->

        <hr>

        <!-- Project Three -->
        <div class="row">
            <div class="col-md-7">
              <!--
              <a href="http://opendata.pol.una.py/?p=88#visualizacion" target="_blank">
                  <%#= image_tag 'viz/administrativos.png', class: 'img-responsive' %>
                </a>
              -->
              <%= link_to image_tag('viz/administrativos.png', class: 'img-responsive'), mec_custom_url(app_academia_funcionarios_administrativos_url) %>
            </div>
            <div class="col-md-5">
                <h3>Funcionarios Administrativos</h3>
                <h4>Del MEC</h4>
                <p>Ver el <a href="http://opendata.pol.una.py/?p=88" target="_blank">blog</a>.</p>
                <%= link_to "Ir a la visualizaci&oacute;n<span class='glyphicon glyphicon-chevron-right'></span>".html_safe, mec_custom_url(app_academia_funcionarios_administrativos_url), class: 'btn btn-primary' %>
                <!--
                <a class="btn btn-primary" href="http://opendata.pol.una.py/?p=88#visualizacion" target="_blank">Ir a la visualización<span class="glyphicon glyphicon-chevron-right"></span></a>
                -->
            </div>
        </div>
        <!-- /.row -->

        <hr>

        <!-- Project Four -->
        <div class="row">

            <div class="col-md-7">
              <!--
              <a href="http://opendata.pol.una.py/?p=53#visualizacion" target="_blank">
                  <%#= image_tag 'viz/rodados.png', class: 'img-responsive' %>
                </a>
              -->
              <%= link_to image_tag('viz/rodados.png', class: 'img-responsive'), mec_custom_url(app_academia_inventario_bienes_rodados_url) %>
            </div>
            <div class="col-md-5">
                <h3>Inventario de Bienes</h3>
                <h4>Rodados</h4>
                <p>Ver el <a href="http://opendata.pol.una.py/?p=53" target="_blank">blog</a>.</p>
                <%= link_to "Ir a la visualizaci&oacute;n<span class='glyphicon glyphicon-chevron-right'></span>".html_safe, mec_custom_url(app_academia_inventario_bienes_rodados_url), class: 'btn btn-primary' %>
                <!--
                <a class="btn btn-primary" href="http://opendata.pol.una.py/?p=53#visualizacion" target="_blank">Ir a la visualización<span class="glyphicon glyphicon-chevron-right"></span></a>
                -->
            </div>
        </div>
        <!-- /.row -->

        <hr>

        <!-- Project Five -->
        <div class="row">
            <div class="col-md-7">
                <!--
                <a href="http://opendata.pol.una.py/?p=191#visualizacion" target="_blank">
                  <%#= image_tag 'viz/inmuebles.png', class: 'img-responsive'%>
                </a>
                -->
                <%= link_to image_tag('viz/inmuebles.png', class: 'img-responsive'), mec_custom_url(app_academia_inventario_bienes_inmuebles_url) %>
            </div>
            <div class="col-md-5">
                <h3>Inventario de Bienes</h3>
                <h4>Inmuebles</h4>
                <p>Ver el <a href="http://opendata.pol.una.py/?p=191" target="_blank">blog</a>.</p>
                <%= link_to "Ir a la visualizaci&oacute;n<span class='glyphicon glyphicon-chevron-right'></span>".html_safe, mec_custom_url(app_academia_inventario_bienes_inmuebles_url), class: 'btn btn-primary' %>
                <!--
                <a class="btn btn-primary" href="http://opendata.pol.una.py/?p=191#visualizacion" target="_blank">Ir a la visualización<span class="glyphicon glyphicon-chevron-right"></span></a>
                -->
            </div>
        </div>
        <hr>

        <!-- Project Five -->
        <div class="row">
            <div class="col-md-7">
              <!--
              <a href="http://opendata.pol.una.py/OpenDataGui/Graficos.seam" target="_blank">
                  <%= image_tag 'viz/muebles.png', class: 'img-responsive' %>
                </a>
              -->
              <%= link_to image_tag('viz/muebles.png', class: 'img-responsive'), mec_custom_url(app_academia_inventario_bienes_muebles_url) %>

            </div>
            <div class="col-md-5">
                <h3>Inventario de Bienes</h3>
                <h4>Muebles</h4>
                <p>Ver el <a href="http://opendata.pol.una.py/?p=114" target="_blank">blog</a>.</p>
                <%= link_to "Ir a la visualizaci&oacute;n<span class='glyphicon glyphicon-chevron-right'></span>".html_safe, mec_custom_url(app_academia_inventario_bienes_muebles_url), class: 'btn btn-primary' %>
                <!--
                <p>Ver el <a href="http://opendata.pol.una.py/?p=114" target="_blank">blog</a></p>
                <a class="btn btn-primary" href="http://opendata.pol.una.py/OpenDataGui/Graficos.seam" target="_blank">Ir a la visualización<span class="glyphicon glyphicon-chevron-right"></span></a>
                -->
            </div>
        </div>
        <!-- /.row -->

        <hr>


		</div>
  </div>

  <style type="text/css">
    
    .menu-tab { 
      width:100%;
      margin-top:10px;
      margin-bottom:10px;
    }

    .menu-tab div {
      width:50%;
      float:left;
      font-size:25px;
      text-align:center;
      border:1px solid silver;
      -moz-border-radius-topleft: 5px;
      -moz-border-radius-topright:5px;
      -moz-border-radius-bottomleft:5px;
      -moz-border-radius-bottomright:5px;
      -webkit-border-top-left-radius:5px;
      -webkit-border-top-right-radius:5px;
      -webkit-border-bottom-left-radius:5px;
      -webkit-border-bottom-right-radius:5px;
      border-top-left-radius:5px;
      border-top-right-radius:5px;
      border-bottom-left-radius:5px;
      border-bottom-right-radius:5px;
    }

  </style>