config/routes.rb
OpenData::Application.routes.draw do

  match "data/establecimientos_escolares_priorizados_elegibles_fonacide" => 'requerimientos_infraestructuras#catalogo', :as => :data_requerimientos_infraestructuras_catalogo

  match 'app/academia/inventario_bienes_muebles' => 'visualizaciones#academia_inventario_bienes_muebles', :as => :app_academia_inventario_bienes_muebles
  match 'app/academia/inventario_bienes_inmuebles' => 'visualizaciones#academia_inventario_bienes_inmuebles', :as => :app_academia_inventario_bienes_inmuebles
  match 'app/academia/inventario_bienes_rodados' => 'visualizaciones#academia_inventario_bienes_rodados', :as => :app_academia_inventario_bienes_rodados
  match 'app/academia/funcionarios_administrativos' => 'visualizaciones#academia_funcionarios_administrativos', :as => :app_academia_funcionarios_administrativos
  match 'app/academia/funcionarios_docentes' => 'visualizaciones#academia_funcionarios_docentes', :as => :app_academia_funcionarios_docentes
  match "data/visualizaciones" => 'visualizaciones#index', :as => :data_visualizaciones
  
  match "data/registros_titulos_lista" => 'registros_titulos#lista', :as => :data_registros_titulos_lista
  match 'data/registros_titulos' => 'registros_titulos#index', :as => :data_registros_titulos
  match 'def/registros_titulos' => 'registros_titulos#diccionario', :as => :def_registros_titulos

  match 'app/mapa_matriculaciones' => 'mapa_matriculaciones#index', :as => :app_mapa_matriculaciones

  match "data/contrataciones_lista" => 'contrataciones#lista', :as => :data_contrataciones_lista
  match 'data/contrataciones' => 'contrataciones#index', :as => :data_contrataciones
  match 'def/contrataciones' => 'contrataciones#diccionario', :as => :def_contrataciones

  match "id/nomina_administrativos/:codigo_trabajador" => "nominas#administrativo_doc", :as => :id_nomimas_administrativo
  match "doc/nomina_administrativos/:codigo_trabajador" =>"nominas#administrativo_doc", :as => :doc_nomimas_administrativo
  match "data/nomina_administrativos_detalles" => 'nominas#detalles', :as => :data_nomina_administrativos_detalles
  match "data/nomina_administrativos_lista" => 'nominas#lista', :as => :data_nomina_administrativos_lista
  match 'data/nomina_administrativos' => 'nominas#index', :as => :data_nomina_administrativos
  match 'def/nomina_administrativos' => 'nominas#diccionario', :as => :def_nomina_administrativos
  match "id/nomina_docentes/:codigo_trabajador" => "nominas#docentes_doc", :as => :id_nomimas_docentes
  match "doc/nomina_docentes/:codigo_trabajador" =>"nominas#docentes_doc", :as => :doc_nomimas_docentes
  match "data/nomina_docentes_detalles" => 'nominas#docentes_detalles', :as => :data_nomina_docentes_detalles
  match "data/nomina_docentes_lista" => 'nominas#docentes_lista', :as => :data_nomina_docentes_lista
  match 'data/nomina_docentes' => 'nominas#docentes', :as => :data_nomina_docentes
  match 'def/nomina_docentes' => 'nominas#docentes_diccionario', :as => :def_nomina_docentes

  match "data/matriculaciones_educacion_permanente_lista" => 'matriculaciones_educacion_permanente#lista', :as => :data_matriculaciones_educacion_permanente_lista
  match 'data/matriculaciones_educacion_permanente' => 'matriculaciones_educacion_permanente#index', :as => :data_matriculaciones_educacion_permanente
  match 'def/matriculaciones_educacion_permanente' => 'matriculaciones_educacion_permanente#diccionario', :as => :def_matriculaciones_educacion_permanente

  match "data/matriculaciones_educacion_inclusiva_lista" => 'matriculaciones_educacion_inclusiva#lista', :as => :data_matriculaciones_educacion_inclusiva_lista
  match 'data/matriculaciones_educacion_inclusiva' => 'matriculaciones_educacion_inclusiva#index', :as => :data_matriculaciones_educacion_inclusiva
  match 'def/matriculaciones_educacion_inclusiva' => 'matriculaciones_educacion_inclusiva#diccionario', :as => :def_matriculaciones_educacion_inclusiva

  match "data/matriculaciones_media_lista" => 'matriculaciones_media#lista', :as => :data_matriculaciones_media_lista
  match 'data/matriculaciones_media' => 'matriculaciones_media#index', :as => :data_matriculaciones_media
  match 'def/matriculaciones_media' => 'matriculaciones_media#diccionario', :as => :def_matriculaciones_media

  match "data/matriculaciones_inicial_lista" => 'matriculaciones_inicial#lista', :as => :data_matriculaciones_inicial_lista
  match 'data/matriculaciones_inicial' => 'matriculaciones_inicial#index', :as => :data_matriculaciones_inicial
  match 'def/matriculaciones_inicial' => 'matriculaciones_inicial#diccionario', :as => :def_matriculaciones_inicial

  match "data/matriculaciones_educacion_escolar_basica_lista" => 'matriculaciones_educacion_escolar_basica#lista', :as => :data_matriculaciones_educacion_escolar_basica_lista
  match 'data/matriculaciones_educacion_escolar_basica' => 'matriculaciones_educacion_escolar_basica#index', :as => :data_matriculaciones_educacion_escolar_basica
  match 'def/matriculaciones_educacion_escolar_basica' => 'matriculaciones_educacion_escolar_basica#diccionario', :as => :def_matriculaciones_educacion_escolar_basica

  match "data/matriculaciones_departamentos_distritos_lista" => 'matriculaciones_departamentos_distritos#lista', :as => :data_matriculaciones_departamentos_distritos_lista
  match 'data/matriculaciones_departamentos_distritos' => 'matriculaciones_departamentos_distritos#index', :as => :data_matriculaciones_departamentos_distritos
  match 'def/matriculaciones_departamentos_distritos' => 'matriculaciones_departamentos_distritos#diccionario', :as => :def_matriculaciones_departamentos_distritos

  match "data/matriculaciones_educacion_media_lista" => 'matriculaciones_educacion_media#lista', :as => :data_matriculaciones_educacion_media_lista
  match 'data/matriculaciones_educacion_media' => 'matriculaciones_educacion_media#index', :as => :data_matriculaciones_educacion_media
  match 'def/matriculaciones_educacion_media' => 'matriculaciones_educacion_media#diccionario', :as => :def_matriculaciones_educacion_media
  
  match "data/matriculaciones_educacion_superior_lista" => 'matriculaciones_educacion_superior#lista', :as => :data_matriculaciones_educacion_superior_lista
  match 'data/matriculaciones_educacion_superior' => 'matriculaciones_educacion_superior#index', :as => :data_matriculaciones_educacion_superior
  match 'def/matriculaciones_educacion_superior' => 'matriculaciones_educacion_superior#diccionario', :as => :def_matriculaciones_educacion_superior

  match "id/instituciones/:codigo_institucion" => "instituciones#doc", :as => :id_instituciones
  match "doc/instituciones/:codigo_institucion" => "instituciones#doc", :as => :doc_instituciones
  match "data/instituciones_lista" => 'instituciones#lista', :as => :data_instituciones_lista
  match 'data/instituciones' => 'instituciones#index', :as => :data_instituciones
  match 'def/instituciones' => 'instituciones#diccionario', :as => :def_instituciones
  
=begin
  match "id/directorios_instituciones/:codigo_institucion" => "directorios_instituciones#doc", :as => :id_instituciones
  match "doc/directorios_instituciones/:codigo_institucion" => "directorios_instituciones#doc", :as => :doc_directorios_instituciones
=end
  match "data/directorios_instituciones_lista" => 'directorios_instituciones#lista', :as => :data_directorios_instituciones_lista
  match 'data/directorios_instituciones' => 'directorios_instituciones#index', :as => :data_directorios_instituciones
  match 'def/directorios_instituciones' => 'directorios_instituciones#diccionario', :as => :def_directorios_instituciones
  
  match "data/requerimientos_aulas_lista" => 'requerimientos_aulas#lista', :as => :data_requerimientos_aulas_lista
  match 'data/requerimientos_aulas' => 'requerimientos_aulas#index', :as => :data_requerimientos_aulas
  match 'def/requerimientos_aulas' => 'requerimientos_aulas#diccionario', :as => :def_requerimientos_aulas
  
  match "data/requerimientos_sanitarios_lista" => 'requerimientos_sanitarios#lista', :as => :data_requerimientos_sanitarios_lista
  match 'data/requerimientos_sanitarios' => 'requerimientos_sanitarios#index', :as => :data_requerimientos_sanitarios
  match 'def/requerimientos_sanitarios' => 'requerimientos_sanitarios#diccionario', :as => :def_requerimientos_sanitarios
  
  match "data/requerimientos_mobiliarios_lista" => 'requerimientos_mobiliarios#lista', :as => :data_requerimientos_mobiliarios_lista
  match 'data/requerimientos_mobiliarios' => 'requerimientos_mobiliarios#index', :as => :data_requerimientos_mobiliarios
  match 'def/requerimientos_mobiliarios' => 'requerimientos_mobiliarios#diccionario', :as => :def_requerimientos_mobiliarios
  
  match "data/requerimientos_otros_espacios_lista" => 'requerimientos_otros_espacios#lista', :as => :data_requerimientos_otros_espacios_lista
  match 'data/requerimientos_otros_espacios' => 'requerimientos_otros_espacios#index', :as => :data_requerimientos_otros_espacios
  match 'def/requerimientos_otros_espacios' => 'requerimientos_otros_espacios#diccionario', :as => :def_requerimientos_otros_espacios
  
  match "data/requerimientos_alimentacion_lista" => 'requerimientos_alimentacion#lista', :as => :data_requerimientos_alimentacion_lista
  match 'data/requerimientos_alimentacion' => 'requerimientos_alimentacion#index', :as => :data_requerimientos_alimentacion
  match 'def/requerimientos_alimentacion' => 'requerimientos_alimentacion#diccionario', :as => :def_requerimientos_alimentacion
  
  match "data/servicios_basicos_lista" => 'servicios_basicos#lista', :as => :data_servicios_basicos_lista
  match 'data/servicios_basicos' => 'servicios_basicos#index', :as => :data_servicios_basicos
  match 'def/servicios_basicos' => 'servicios_basicos#diccionario', :as => :def_servicios_basicos

  match "id/establecimientos/:codigo_establecimiento" => "data#establecimientos_doc", :as => :id_establecimientos

app/helpers/matriculaciones_educacion_superior.rb
module MatriculacionesEducacionSuperiorHelper
  
end

app/views/matriculaciones_educacion_superior/_infowindow_matriculacion_educacion_superior.html.erb
<table class="table table-striped table-bordered table-hover">

  <tr>
    <th>Departamento</th>
    <td><%= matriculacion_educacion_superior.nombre_departamento %></td>
  </tr>

  <tr>
    <th>Distrito</th>
    <td><%= matriculacion_educacion_superior.nombre_distrito %></td>
  </tr>

  <tr>
    <th>Barrio/Localidad</th>
    <td><%= matriculacion_educacion_superior.nombre_barrio_localidad %></td>
  </tr>

  <tr>
    <th>Zona</th>
    <td><%= matriculacion_educacion_superior.nombre_zona %></td>
  </tr>

  <tr>
    <th>Sector o Tipo de Gestión</th>
    <td><%= matriculacion_educacion_superior.sector_o_tipo_gestion %></td>
  </tr>

  <tr>
    <th>Establecimiento</th>
    <td><%= matriculacion_educacion_superior.codigo_establecimiento %></td>
  </tr>

  <tr>
    <th>Institución</th>
    <td><%= matriculacion_educacion_superior.nombre_institución %></td>
  </tr>

  <tr>
    <th>Cantidad de Matriculados - Nivel Terciario</th>
    <td><%= matriculacion_educacion_superior.matricula_ets%></td>
  </tr>

  <tr>
    <th>Cantidad de Matriculados - Cursos de Profesorado</th>
    <td><%= matriculacion_educacion_superior.matricula_fed%></td>
  </tr>

  <tr>
    <th>Cantidad de Matriculados - Formación Docente</th>
    <td><%= matriculacion_educacion_superior.matricula_fdes%></td>
  </tr>

  <tr>
    <th>Cantidad de Matriculados - Nivel Terciario</th>
    <td><%= matriculacion_educacion_superior.matricula_pd%></td>
  </tr>

</table>

app/views/matriculaciones_educacion_superior/_lista.html.erb
<% if matriculaciones_educacion_superior.present? %>
  
  <% matriculaciones_educacion_superior.each do |e| %>

    <tr>

      <td class="text-min"><%= e.anio %></td>
      <td class="text-min"><b>
      	<%#= link_to e.codigo_establecimiento, mec_custom_url(data_establecimientos_path(:ce => e.codigo_establecimiento)), :target => "_blank", :title => "Ir al dataset de establecimientos" %>
      	<%= link_to e.codigo_establecimiento, mec_custom_url(id_establecimientos_path(e.codigo_establecimiento)), target: '_blank',style: 'font-weight:bold;', title: 'Visualizar URI' %>
      	
      	</b></td>     
      <td class="text-min"><b>
      	<%#= link_to e.codigo_institucion, mec_custom_url(data_instituciones_path(:ci => e.codigo_institucion)), :target => "_target", :title => "Ir al dataset de instituciones" %>
      	<%= link_to e.codigo_institucion, mec_custom_url(id_instituciones_path(e.codigo_institucion)), target: '_blank',style: 'font-weight:bold;', title: 'Visualizar URI' %>
      	
      	</b></td>
      <td class="text-min"><%= e.nombre_institucion %></td>
      <td class="text-min"><%= e.nombre_departamento %></td>
      <td class="text-min"><%= e.nombre_distrito %></td>
      <td class="text-min"><%= e.nombre_barrio_localidad %></td>
      <td class="text-min"><%= e.nombre_zona %></td>
      <td class="text-min"><%= e.sector_o_tipo_gestion %></td>
      <td class="text-min"><%= e.matricula_ets %></td>       
      <td class="text-min"><%= e.matricula_fed %></td>       
      <td class="text-min"><%= e.matricula_fdes %></td>       
      <td class="text-min"><%= e.matricula_pd %></td>       
    </tr>
  
  <% end %>
  
  <% else %>

  <tr>
    
    <td colspan="13"><p class='none-result'>No se han encontrado resultados.</p></td>
  
  </tr>

<% end %>

app/views/matriculaciones_educacion_superior/index.html.erb
<h2>
  <span itemprop="name">Matriculaciones Educación Superior</span>
  <meta itemprop="description" content="Se refiere a la cantidad de matriculados en las diferentes modalidades de educación superior con sus correspondientes códigos identificatorios."/>
  <meta itemprop="url" content="http://datos.mec.gov.py/data/matriculaciones_educacion_superior">
  <meta itemprop="temporal" style="display: none;" content="2012-01-01/2012-12-31"/>
  <span itemprop="catalog" itemscope itemtype="https://schema.org/DataCatalog" style="display: none;">
    <meta itemprop="name" content="Datos Abiertos del Ministerio de Educación y Cultura">
    <meta itemprop="url" content="http://datos.mec.gov.py/">
    <meta itemprop="description" content="Datos Abiertos del Ministerio de Educación y Cultura">
  </span>
  <span itemprop="provider" itemscope itemtype="https://schema.org/Organization" style="display: none;">
    <meta itemprop="name" content="Ministerio de Educación y Cultura">
    <meta itemprop="url" content="http://www.mec.gov.py/">
    <meta itemprop="email" content="datosabiertos@mec.gov.py">
  </span>
  <span itemprop="creator" itemscope itemtype="https://schema.org/Person" style="display: none;">
    <meta itemprop="name" content="Juan Barrios">
    <meta itemprop="email" content="datosabiertos@mec.gov.py">
  </span>
  <meta itemprop="license" style="display: none;" content="https://creativecommons.org/licenses/by/4.0/legalcode"/>
  <meta itemprop="keywords" style="display: none;" content="educación,matriculaciones,educación superior"/>
  <meta itemprop="version" style="display: none;" content="1.0"/>
  <span style="float:right;">
    <%= link_to "Ver diccionario", mec_custom_url(def_matriculaciones_educacion_superior_url), :title => "Ir al diccionario", :style => "font-size:12px;" %>
    <%= link_to image_tag("def_icon.png", :style => "width:24px;" ), mec_custom_url(def_matriculaciones_educacion_superior_url), :title => "Ir al diccionario" %>
    <%= link_to "Inicio", mec_custom_url(index_url), :title => "Ir al inicio", :style => "font-size:12px;" %>
    <%= link_to image_tag("home.png", :style => "width:24px;"), mec_custom_url(index_url), :title => "Ir al inicio" %>
  </span>

</h2>

<div class="table-outter">
  <table id="matriculaciones-educacion-superior-table" class="table table-striped table-bordered table-hover" style="margin-bottom: 0px; width: 2000px; max-width: none">

    <tr>

      <%= form_tag mec_custom_url(data_matriculaciones_educacion_superior_lista_url(nil,nil)), :remote => true, :id => "form-buscar-matriculaciones-educacion-superior" do  %>

        <th style="width:5%" class="text-min celda-derecha">
          <%= label_tag "Periodo" %><br /><br />
          <%= select :form_buscar_matriculaciones_educacion_superior, :anio, [2012], {:class => 'text-min'} %>
          <%= link_to_function icon_delete, "quitar_filtro($('#form_buscar_matriculaciones_educacion_superior_anio'),1);" %>
        </th>

        <th style="width:7%" class="text-min">
          <%= label_tag nil, "C&oacute;digo Establecimiento".html_safe%><br /><br />
          <%= text_field_tag :form_buscar_matriculaciones_educacion_superior_codigo_establecimiento, nil, :class => 'text-min' %>
          <%= link_to_function icon_delete, "quitar_filtro($('#form_buscar_matriculaciones_educacion_superior_codigo_establecimiento'));" %>
        </th>

        <th style="width:7%" class="text-min">
          <%= label_tag nil, "C&oacute;digo de Institución".html_safe %><br /><br />
          <%= text_field_tag :form_buscar_matriculaciones_educacion_superior_codigo_institucion, nil, :class => 'text-min' %>
          <%= link_to_function icon_delete, "quitar_filtro($('#form_buscar_matriculaciones_educacion_superior_codigo_institucion'));" %>
        </th>


        <th style="width:7%" class="text-min">
          <%= label_tag "Institución"%><br /><br />
          <%= text_field_tag :form_buscar_matriculaciones_educacion_superior_nombre_institucion, nil, :class => 'text-min' %>
          <%= link_to_function icon_delete, "quitar_filtro($('#form_buscar_matriculaciones_educacion_superior_nombre_institucion'));" %>
        </th>


        <th style="width:7%" class="text-min">
          <%= label_tag "Departamento"%><br /><br />
          <%= text_field_tag :form_buscar_matriculaciones_educacion_superior_nombre_departamento, nil, :class => 'text-min' %>
          <%= link_to_function icon_delete, "quitar_filtro($('#form_buscar_matriculaciones_educacion_superior_nombre_departamento'));" %>
        </th>

        <th style="width:7%" class="text-min">
          <%= label_tag "Distrito"%><br /><br />
          <%= text_field_tag :form_buscar_matriculaciones_educacion_superior_nombre_distrito, nil, :class => 'text-min' %>
          <%= link_to_function icon_delete, "quitar_filtro($('#form_buscar_matriculaciones_educacion_superior_nombre_distrito'));" %>
        </th>

        <th style="width:7%" class="text-min">
          <%= label_tag "Barrio/Localidad"%><br /><br />
          <%= text_field_tag :form_buscar_matriculaciones_educacion_superior_nombre_barrio_localidad, nil, :class => 'text-min' %>
          <%= link_to_function icon_delete, "quitar_filtro($('#form_buscar_matriculaciones_educacion_superior_nombre_barrio_localidad'));" %>
        </th>

        <th style="width:7%" class="text-min">
          <%= label_tag "Zona"%><br /><br />
          <%= text_field_tag :form_buscar_matriculaciones_educacion_superior_nombre_zona, nil, :class => 'text-min' %>
          <%= link_to_function icon_delete, "quitar_filtro($('#form_buscar_matriculaciones_educacion_superior_nombre_zona'));" %>
        </th>

        <th style="width:7%" class="text-min">
          <%= label_tag "Sector o Tipo de Gestión"%><br /><br />
          <%= text_field_tag :form_buscar_matriculaciones_educacion_superior_sector_o_tipo_gestion, nil, :class => 'text-min' %>
          <%= link_to_function icon_delete, "quitar_filtro($('#form_buscar_matriculaciones_educacion_superior_sector_o_tipo_gestion'));" %>
        </th>

        <th style="width:7%;" class="text-min">
          <%= label_tag nil, "Cantidad de Matriculados\n Nivel Terciario".html_safe%><br />
          <%= select_tag(:form_buscar_matriculaciones_educacion_superior_matricula_ets_operador, options_for_select(['>', '<', '='])) %>
          <%= text_field_tag :form_buscar_matriculaciones_educacion_superior_matricula_ets, nil, :class => 'text-min' %>
          <%= link_to_function icon_delete, "quitar_filtro($('#form_buscar_matriculaciones_educacion_superior_matricula_ets'));" %>
        </th>

        <th style="width:7%;" class="text-min">
          <%= label_tag nil, "Cantidad de Matriculados\n Cursos de Profesorado".html_safe%><br />
          <%= select_tag(:form_buscar_matriculaciones_educacion_superior_matricula_fed_operador, options_for_select(['>', '<', '='])) %>
          <%= text_field_tag :form_buscar_matriculaciones_educacion_superior_matricula_fed, nil, :class => 'text-min' %>
          <%= link_to_function icon_delete, "quitar_filtro($('#form_buscar_matriculaciones_educacion_superior_matricula_fed'));" %>
        </th>

        <th style="width:7%;" class="text-min">
          <%= label_tag nil, "Cantidad de Matriculados\n Formación Docente".html_safe%><br />
          <%= select_tag(:form_buscar_matriculaciones_educacion_superior_matricula_fdes_operador, options_for_select(['>', '<', '='])) %>
          <%= text_field_tag :form_buscar_matriculaciones_educacion_superior_matricula_fdes, nil, :class => 'text-min' %>
          <%= link_to_function icon_delete, "quitar_filtro($('#form_buscar_matriculaciones_educacion_superior_matricula_fdes'));" %>
        </th>

        <th style="width:7%;" class="text-min">
          <%= label_tag nil, "Cantidad de Matriculados\n Profesionalización Docente".html_safe%><br />
          <%= select_tag(:form_buscar_matriculaciones_educacion_superior_matricula_pd_operador, options_for_select(['>', '<', '='])) %>
          <%= text_field_tag :form_buscar_matriculaciones_educacion_superior_matricula_pd, nil, :class => 'text-min' %>
          <%= link_to_function icon_delete, "quitar_filtro($('#form_buscar_matriculaciones_educacion_superior_matricula_pd'));" %>
        </th>
      <% end %>

    </tr>

    <tbody id="matriculaciones-educacion-superior-lista"></tbody>

  </table>
</div>

<table class="table table-striped table-bordered table-hover">
  <tbody id="matriculaciones-educacion-superior-footer"></tbody>
</table>


<script type="text/javascript">

  $("#form-buscar-matriculaciones-educacion-superior").bind("submit", function() {

    $("#matriculaciones-educacion-superior-lista").html("<%= escape_javascript("<tr><td colspan='11' style='text-align:center;'>#{image_tag('ajax-loader0.gif')}</td></tr>").html_safe %>")

  })

  $("#form_buscar_matriculaciones_educacion_superior_anio").bind('change', function() {
    $.ajaxQ.abortAll();
    $("#form-buscar-matriculaciones-educacion-superior").submit();

  })

  $(".table-bordered :input").bind('change', function() {
    $.ajaxQ.abortAll();
    $("#form-buscar-matriculaciones-educacion-superior").submit();

  })

  //LIMPIAR FORMULARIO DE BUSQUEDA
  function limpiar_form_buscar_matriculaciones_educacion_superior() {

    $("#form_buscar_matriculaciones_educacion_superior_anio").val("2012");
    $("#form_buscar_matriculaciones_educacion_superior_nombre_departamento").val("");
    $("#form_buscar_matriculaciones_educacion_superior_nombre_distrito").val("");
    $("#form_buscar_matriculaciones_educacion_superior_nombre_barrio_localidad").val("");
    $("#form_buscar_matriculaciones_educacion_superior_nombre_zona").val("");
    $("#form_buscar_matriculaciones_educacion_superior_codigo_establecimiento").val("");
    $("#form_buscar_matriculaciones_educacion_superior_nombre_institucion").val("");
    $("#form_buscar_matriculaciones_educacion_superior_sector_o_tipo_gestion").val("");
    $("#form_buscar_matriculaciones_educacion_superior_matriculados_matricula_ets").val("");
    $("#form_buscar_matriculaciones_educacion_superior_matricula_fed").val("");
    $("#form_buscar_matriculaciones_educacion_superior_matricula_fdes").val("");
    $("#form_buscar_matriculaciones_educacion_superior_matricula_pd").val("");
    $.ajaxQ.abortAll();
    $("#form-buscar-matriculaciones-educacion-superior").submit();

  }

  limpiar_form_buscar_matriculaciones_educacion_superior();

  //--------------- QUITAR FILTRO -------------------//
  function quitar_filtro(id, ban) {
    if (ban === 1) {
      id.val("2012");
    } else {
      id.val('');
    }
    $.ajaxQ.abortAll();
    $('#form-buscar-matriculaciones-educacion-superior').submit();

  }
  //-------------------------------------------------//

</script>

<style>

  .text-min {font-size:9px !important; color: #000; text-align:center !important;}
  #cbue-menu1 {background:#e9e9e9;}
  .text-min input[type="text"], .text-min select {
    border: 1px solid silver;
    padding: 3px;
    -webkit-border-radius: 5px 5px 5px 5px;
    border-radius: 5px 5px 5px 5px;
    color:#000;
  }
  .text-min input[type="text"] { width: 80px;}
  #tablaContenedor{width:100%;}

</style>