config/routes.rb
OpenData::Application.routes.draw do

  match "data/establecimientos_escolares_priorizados_elegibles_fonacide" => 'requerimientos_infraestructuras#catalogo', :as => :data_requerimientos_infraestructuras_catalogo

  match 'app/academia/inventario_bienes_muebles' => 'visualizaciones#academia_inventario_bienes_muebles', :as => :app_academia_inventario_bienes_muebles
  match 'app/academia/inventario_bienes_inmuebles' => 'visualizaciones#academia_inventario_bienes_inmuebles', :as => :app_academia_inventario_bienes_inmuebles
  match 'app/academia/inventario_bienes_rodados' => 'visualizaciones#academia_inventario_bienes_rodados', :as => :app_academia_inventario_bienes_rodados
  match 'app/academia/funcionarios_administrativos' => 'visualizaciones#academia_funcionarios_administrativos', :as => :app_academia_funcionarios_administrativos
  match 'app/academia/funcionarios_docentes' => 'visualizaciones#academia_funcionarios_docentes', :as => :app_academia_funcionarios_docentes
  match "data/visualizaciones" => 'visualizaciones#index', :as => :data_visualizaciones
  
  match "data/registros_titulos_lista" => 'registros_titulos#lista', :as => :data_registros_titulos_lista
  match 'data/registros_titulos' => 'registros_titulos#index', :as => :data_registros_titulos
  match 'def/registros_titulos' => 'registros_titulos#diccionario', :as => :def_registros_titulos

  match 'app/mapa_matriculaciones' => 'mapa_matriculaciones#index', :as => :app_mapa_matriculaciones

  match "data/contrataciones_lista" => 'contrataciones#lista', :as => :data_contrataciones_lista
  match 'data/contrataciones' => 'contrataciones#index', :as => :data_contrataciones
  match 'def/contrataciones' => 'contrataciones#diccionario', :as => :def_contrataciones

  match "id/nomina_administrativos/:codigo_trabajador" => "nominas#administrativo_doc", :as => :id_nomimas_administrativo
  match "doc/nomina_administrativos/:codigo_trabajador" =>"nominas#administrativo_doc", :as => :doc_nomimas_administrativo
  match "data/nomina_administrativos_detalles" => 'nominas#detalles', :as => :data_nomina_administrativos_detalles
  match "data/nomina_administrativos_lista" => 'nominas#lista', :as => :data_nomina_administrativos_lista
  match 'data/nomina_administrativos' => 'nominas#index', :as => :data_nomina_administrativos
  match 'def/nomina_administrativos' => 'nominas#diccionario', :as => :def_nomina_administrativos
  match "id/nomina_docentes/:codigo_trabajador" => "nominas#docentes_doc", :as => :id_nomimas_docentes
  match "doc/nomina_docentes/:codigo_trabajador" =>"nominas#docentes_doc", :as => :doc_nomimas_docentes
  match "data/nomina_docentes_detalles" => 'nominas#docentes_detalles', :as => :data_nomina_docentes_detalles
  match "data/nomina_docentes_lista" => 'nominas#docentes_lista', :as => :data_nomina_docentes_lista
  match 'data/nomina_docentes' => 'nominas#docentes', :as => :data_nomina_docentes
  match 'def/nomina_docentes' => 'nominas#docentes_diccionario', :as => :def_nomina_docentes

  match "data/matriculaciones_educacion_permanente_lista" => 'matriculaciones_educacion_permanente#lista', :as => :data_matriculaciones_educacion_permanente_lista
  match 'data/matriculaciones_educacion_permanente' => 'matriculaciones_educacion_permanente#index', :as => :data_matriculaciones_educacion_permanente
  match 'def/matriculaciones_educacion_permanente' => 'matriculaciones_educacion_permanente#diccionario', :as => :def_matriculaciones_educacion_permanente

  match "data/matriculaciones_educacion_inclusiva_lista" => 'matriculaciones_educacion_inclusiva#lista', :as => :data_matriculaciones_educacion_inclusiva_lista
  match 'data/matriculaciones_educacion_inclusiva' => 'matriculaciones_educacion_inclusiva#index', :as => :data_matriculaciones_educacion_inclusiva
  match 'def/matriculaciones_educacion_inclusiva' => 'matriculaciones_educacion_inclusiva#diccionario', :as => :def_matriculaciones_educacion_inclusiva

  match "data/matriculaciones_media_lista" => 'matriculaciones_media#lista', :as => :data_matriculaciones_media_lista
  match 'data/matriculaciones_media' => 'matriculaciones_media#index', :as => :data_matriculaciones_media
  match 'def/matriculaciones_media' => 'matriculaciones_media#diccionario', :as => :def_matriculaciones_media

  match "data/matriculaciones_inicial_lista" => 'matriculaciones_inicial#lista', :as => :data_matriculaciones_inicial_lista
  match 'data/matriculaciones_inicial' => 'matriculaciones_inicial#index', :as => :data_matriculaciones_inicial
  match 'def/matriculaciones_inicial' => 'matriculaciones_inicial#diccionario', :as => :def_matriculaciones_inicial

  match "data/matriculaciones_educacion_escolar_basica_lista" => 'matriculaciones_educacion_escolar_basica#lista', :as => :data_matriculaciones_educacion_escolar_basica_lista
  match 'data/matriculaciones_educacion_escolar_basica' => 'matriculaciones_educacion_escolar_basica#index', :as => :data_matriculaciones_educacion_escolar_basica
  match 'def/matriculaciones_educacion_escolar_basica' => 'matriculaciones_educacion_escolar_basica#diccionario', :as => :def_matriculaciones_educacion_escolar_basica

  match "data/matriculaciones_departamentos_distritos_lista" => 'matriculaciones_departamentos_distritos#lista', :as => :data_matriculaciones_departamentos_distritos_lista
  match 'data/matriculaciones_departamentos_distritos' => 'matriculaciones_departamentos_distritos#index', :as => :data_matriculaciones_departamentos_distritos
  match 'def/matriculaciones_departamentos_distritos' => 'matriculaciones_departamentos_distritos#diccionario', :as => :def_matriculaciones_departamentos_distritos

  match "data/matriculaciones_educacion_media_lista" => 'matriculaciones_educacion_media#lista', :as => :data_matriculaciones_educacion_media_lista
  match 'data/matriculaciones_educacion_media' => 'matriculaciones_educacion_media#index', :as => :data_matriculaciones_educacion_media
  match 'def/matriculaciones_educacion_media' => 'matriculaciones_educacion_media#diccionario', :as => :def_matriculaciones_educacion_media
  
  match "data/matriculaciones_educacion_superior_lista" => 'matriculaciones_educacion_superior#lista', :as => :data_matriculaciones_educacion_superior_lista
  match 'data/matriculaciones_educacion_superior' => 'matriculaciones_educacion_superior#index', :as => :data_matriculaciones_educacion_superior
  match 'def/matriculaciones_educacion_superior' => 'matriculaciones_educacion_superior#diccionario', :as => :def_matriculaciones_educacion_superior

  match "id/instituciones/:codigo_institucion" => "instituciones#doc", :as => :id_instituciones
  match "doc/instituciones/:codigo_institucion" => "instituciones#doc", :as => :doc_instituciones
  match "data/instituciones_lista" => 'instituciones#lista', :as => :data_instituciones_lista
  match 'data/instituciones' => 'instituciones#index', :as => :data_instituciones
  match 'def/instituciones' => 'instituciones#diccionario', :as => :def_instituciones
  
=begin
  match "id/directorios_instituciones/:codigo_institucion" => "directorios_instituciones#doc", :as => :id_instituciones
  match "doc/directorios_instituciones/:codigo_institucion" => "directorios_instituciones#doc", :as => :doc_directorios_instituciones
=end
  match "data/directorios_instituciones_lista" => 'directorios_instituciones#lista', :as => :data_directorios_instituciones_lista
  match 'data/directorios_instituciones' => 'directorios_instituciones#index', :as => :data_directorios_instituciones
  match 'def/directorios_instituciones' => 'directorios_instituciones#diccionario', :as => :def_directorios_instituciones
  
  match "data/requerimientos_aulas_lista" => 'requerimientos_aulas#lista', :as => :data_requerimientos_aulas_lista
  match 'data/requerimientos_aulas' => 'requerimientos_aulas#index', :as => :data_requerimientos_aulas
  match 'def/requerimientos_aulas' => 'requerimientos_aulas#diccionario', :as => :def_requerimientos_aulas
  
  match "data/requerimientos_sanitarios_lista" => 'requerimientos_sanitarios#lista', :as => :data_requerimientos_sanitarios_lista
  match 'data/requerimientos_sanitarios' => 'requerimientos_sanitarios#index', :as => :data_requerimientos_sanitarios
  match 'def/requerimientos_sanitarios' => 'requerimientos_sanitarios#diccionario', :as => :def_requerimientos_sanitarios
  
  match "data/requerimientos_mobiliarios_lista" => 'requerimientos_mobiliarios#lista', :as => :data_requerimientos_mobiliarios_lista
  match 'data/requerimientos_mobiliarios' => 'requerimientos_mobiliarios#index', :as => :data_requerimientos_mobiliarios
  match 'def/requerimientos_mobiliarios' => 'requerimientos_mobiliarios#diccionario', :as => :def_requerimientos_mobiliarios
  
  match "data/requerimientos_otros_espacios_lista" => 'requerimientos_otros_espacios#lista', :as => :data_requerimientos_otros_espacios_lista
  match 'data/requerimientos_otros_espacios' => 'requerimientos_otros_espacios#index', :as => :data_requerimientos_otros_espacios
  match 'def/requerimientos_otros_espacios' => 'requerimientos_otros_espacios#diccionario', :as => :def_requerimientos_otros_espacios
  
  match "data/requerimientos_alimentacion_lista" => 'requerimientos_alimentacion#lista', :as => :data_requerimientos_alimentacion_lista
  match 'data/requerimientos_alimentacion' => 'requerimientos_alimentacion#index', :as => :data_requerimientos_alimentacion
  match 'def/requerimientos_alimentacion' => 'requerimientos_alimentacion#diccionario', :as => :def_requerimientos_alimentacion
  
  match "data/servicios_basicos_lista" => 'servicios_basicos#lista', :as => :data_servicios_basicos_lista
  match 'data/servicios_basicos' => 'servicios_basicos#index', :as => :data_servicios_basicos
  match 'def/servicios_basicos' => 'servicios_basicos#diccionario', :as => :def_servicios_basicos

  match "id/establecimientos/:codigo_establecimiento" => "data#establecimientos_doc", :as => :id_establecimientos

app/models/nomina.rb
class Nomina < ActiveRecord::Base

  self.table_name = "nomina"

  scope :ordenado_anio_mes_nombre, :order => 'ano_periodo_pago, mes_periodo_pago, nombre_trabajador, id_objeto_gasto'

  scope :es_docente, where('es_categoria_administrativa = 0')
  scope :es_administrativo, where('es_categoria_administrativa = 1')

end

app/helpers/nominas_helper.rb
module NominasHelper

  def link_to_nominas_detalles(nomina)

    partial = (nomina.es_categoria_administrativa == 1) ? 'link_to_nominas_detalles' : 'link_to_nomina_docentes_detalles'

		render :partial => partial, :locals => {:nomina => nomina }

	end

  def obtener_total_asignacion(id_trabajador, id_objeto_gasto, es_categoria_administrativa, ano_periodo_pago, mes_periodo_pago)

    nomina = VNomina.find_all_by_id_trabajador_and_id_objeto_gasto_and_es_categoria_administrativa_and_ano_periodo_pago_and_mes_periodo_pago(id_trabajador, id_objeto_gasto, es_categoria_administrativa, ano_periodo_pago, mes_periodo_pago)
    
    asignacion = 0

    nomina.each do |n|
      asignacion += n.asignacion
    end

    asignacion

  end

end

app/views/nominas/_detalles.html.erb
<td colspan="10">

  <hr style="border-bottom: 2px dashed silver;" />
  
  <h3>Detalles de la Asignaci&oacute;n de <span style='color:#000;'><%= @nomina.first.nombre_trabajador %></span></h3>

  <table class="table table-striped table-bordered table-hover" style="font-size:10px;">
    <thead>

      <tr>
        <th>Concepto</th>
        <th><%= @nomina.first.es_categoria_administrativa == 1 ? "Dependencia" : "Instituci&oacute;n".html_safe%></th>
        <th>Cargo</th>
        <th>Categor&iacute;a<br />Rubro</th>
        <th style="text-align:right;">Asignaci&oacute;n <br />Categor&iacute;a<br />Rubro</th>
        <th style="text-align:right;">Cantidad</th>
        <th style="text-align:right;">Asignaci&oacute;n</th>
        <th style="text-align:right;">Devuelto</th>
      </tr>

    </thead>

    <tbody>

      <% @nomina.each do |n| %>

        <tr>
          <td><%= n.nombre_concepto_nomina %></td>
          <td><%= n.nombre_dependencia_efectiva %></td>
          <td><%= n.nombre_cargo_efectivo %></td>
          <td><%= n.codigo_categoria_rubro %></td>
          <td style="text-align:right;"><%= number_to_currency(n.monto_categoria_rubro, :unit => '', :precision => 0) if n.monto_categoria_rubro.present? %></td>
          <td style="text-align:right;"><%= n.cantidad.to_i %></td>
          <td style="text-align:right;"><%= number_to_currency(n.asignacion, :unit => '', :precision => 0) if n.asignacion.present? %></td>
          <td style="text-align:right;"><%= number_to_currency(n.monto_devuelto, :unit => '', :precision => 0) if n.monto_devuelto.present? %></td>
        </tr>

      <% end %>

      <tr style="font-weight:bold;color:#000;">
        <td colspan=6>Total</td>
        <td style="text-align:right;"><%= number_to_currency(obtener_total_asignacion(@nomina.first.id_trabajador, @nomina.first.id_objeto_gasto, @nomina.first.es_categoria_administrativa, @nomina.first.ano_periodo_pago, @nomina.first.mes_periodo_pago), :unit => '', :precision => 0) %></td>
      </tr>

    </tbody>

  </table>

  <hr style="border-bottom: 2px dashed silver;" />

</td>

app/views/nominas/_link_to_nomina_docentes_detalles.html.erb
<%= link_to image_tag("folder_table.png"), "#", :id => "link-to-nominas-detalles-#{nomina.id_trabajador}-#{nomina.id_objeto_gasto}", :title => "Haga click para ver el detalle." %>

<script type="text/javascript">

  $("#link-to-nominas-detalles-<%= nomina.id_trabajador %>-<%= nomina.id_objeto_gasto%>").bind("click", function(){
      
      var tr_size = $.trim($("#nominas-detalles-<%= nomina.id_trabajador %>-<%= nomina.id_objeto_gasto%>").html()).length 

			$('.nominas-detalles').remove();

			if(tr_size == 0){

        $(this).parent().parent().after("<tr id=\"nominas-detalles-<%= nomina.id_trabajador %>-<%= nomina.id_objeto_gasto%>\" class=\"nominas-detalles\"></tr>"); 
        
        $("#nominas-detalles-<%= nomina.id_trabajador %>-<%= nomina.id_objeto_gasto%>").html("<%= escape_javascript("<tr><td style='text-align:center;' colspan='9'>#{image_tag('ajax-loader0.gif')}</td></tr>").html_safe %>")  
          
          $.ajax({
						  type: 'POST',
						  url: "<%= mec_custom_url(data_nomina_docentes_detalles_url) %>",
              data: { id_trabajador:'<%= nomina.id_trabajador %>', 
                      id_objeto_gasto:'<%= nomina.id_objeto_gasto %>', 
                      ano_periodo_pago:'<%= nomina.ano_periodo_pago %>',
                      mes_periodo_pago:'<%= nomina.mes_periodo_pago %>' },
						  dataType: 'script'  
						});

      } 

			return false; 
	 });

</script>

app/views/nominas/_link_to_nominas_detalles.html.erb
<%= link_to image_tag("folder_table.png"), "#", :id => "link-to-nominas-detalles-#{nomina.id_trabajador}-#{nomina.id_objeto_gasto}", :title => "Haga click para ver el detalle." %>

<script type="text/javascript">

  $("#link-to-nominas-detalles-<%= nomina.id_trabajador %>-<%= nomina.id_objeto_gasto%>").bind("click", function(){
      
      var tr_size = $.trim($("#nominas-detalles-<%= nomina.id_trabajador %>-<%= nomina.id_objeto_gasto%>").html()).length 

			$('.nominas-detalles').remove();

			if(tr_size == 0){

        $(this).parent().parent().after("<tr id=\"nominas-detalles-<%= nomina.id_trabajador %>-<%= nomina.id_objeto_gasto%>\" class=\"nominas-detalles\"></tr>"); 
        
        $("#nominas-detalles-<%= nomina.id_trabajador %>-<%= nomina.id_objeto_gasto%>").html("<%= escape_javascript("<tr><td style='text-align:center;' colspan='9'>#{image_tag('ajax-loader0.gif')}</td></tr>").html_safe %>")  
          
          $.ajax({
						  type: 'POST',
						  url: "<%= mec_custom_url(data_nomina_administrativos_detalles_url) %>",
              data: { id_trabajador:'<%= nomina.id_trabajador %>', 
                      id_objeto_gasto:'<%= nomina.id_objeto_gasto %>', 
                      ano_periodo_pago:'<%= nomina.ano_periodo_pago %>',
                      mes_periodo_pago:'<%= nomina.mes_periodo_pago %>' },
						  dataType: 'script'  
						});

      } 

			return false; 
	 });

</script>

app/views/nominas/administrativo_doc.html.erb
<h2>
	<span itemprop="name">Administrativos</span>
  <meta itemprop="description"
    content="Contiene información sobre la ubicación geográfica de los establecimientos escolares tales como el departamento, distrito,barrio/localidad donde se encuentran asentados, además de la zona (urbana o rural) a la cual pertenecen, y los datos georreferenciadas como las coordenadas planas (en metros) y geograficas. El Sistema de informacion de Estadística Continua (SIEC) considera “Establecimiento Escolar” a la construcción que existe dentro de un predio (terreno) que se emplea para la enseñanza, donde puede funcionar una o más instituciones educativas con sus respectivos niveles/modalidades de educación."/>
  <meta itemprop="temporal" style="display: none;" content="2012-01-01/2012-12-31">
  <meta itemprop="url" content="http://datos.mec.gov.py/data/establecimientos">  
  <span itemprop="provider" itemscope itemtype="https://schema.org/Organization" style="display: none;">
    <meta itemprop="name" content="Ministerio de Educación y Cultura">
    <meta itemprop="url" content="http://www.mec.gov.py/">
    <meta itemprop="email" content="datosabiertos@mec.gov.py">
  </span>
  <span itemprop="creator" itemscope itemtype="https://schema.org/Person" style="display: none;">
    <meta itemprop="name" content="Juan Barrios">
    <meta itemprop="email" content="datosabiertos@mec.gov.py">
  </span>
  <meta itemprop="license" style="display: none;" content="https://creativecommons.org/licenses/by/4.0/legalcode"/>
  <meta itemprop="keywords" style="display: none;" content="educación,establecimientos,escolar,geografico"/>
  <meta itemprop="version" style="display: none;" content="1.0"/>
  <span style="float:right;">
    <%= link_to "Ver dataset", mec_custom_url(data_nomina_administrativos_url), :title => "Ir al Dataset", :style => "font-size:12px;" %>
    <%= link_to image_tag("datos_ico.jpg", :style => "width:24px;" ), mec_custom_url(data_nomina_administrativos_url), :title => "Ir al Dataset" %> 
    <%= link_to "Ver diccionario", mec_custom_url(def_nomina_administrativos_url), :title => "Ir al diccionario", :style => "font-size:12px;" %>
    <%= link_to image_tag("def_icon.png", :style => "width:24px;" ), mec_custom_url(def_nomina_administrativos_url), :title => "Ir al diccionario" %>
    <%= link_to "Inicio", mec_custom_url(index_url), :title => "Ir al inicio", :style => "font-size:12px;" %>
    <%= link_to image_tag("home.png", :style => "width:24px;"), mec_custom_url(index_url), :title => "Ir al inicio" %>
  </span>

</h2>

<% if @adminnomina.present? %>


  <div class="uri-data-filter">
  	<%= label_tag "Periodo" %>
    <%= select :form_buscar_nominas, :ano_periodo_pago, [2014], {:class => 'text-min'} %>
    <%= label_tag "Mes" %>
    <%= select :form_buscar_nominas, :mes_periodo_pago, [["octubre", 10]], {:class => 'text-min'} %>
  	
  </div>
  
  <br />
  
  <div class='uri-data-left'>

    <h4>Datos del Administrativo </h4>
    <div class='uri-titulo' style='border-top:1px solid silver;'>Periodo</div><div class='uri-valor first'><%= @adminnomina.ano_periodo_pago %></div><br />
    <div class='uri-titulo'>Mes</div><div class='uri-valor'><%= obtener_mes(@adminnomina.mes_periodo_pago) %></div><br />
    <div class='uri-titulo'>N° documento</div><div class='uri-valor'><%= @adminnomina.codigo_trabajador %></div><br />
    <div class='uri-titulo'>Nombre completo</div><div class='uri-valor'><%=@adminnomina.nombre_trabajador%></div><br />
    <div class='uri-titulo'>Antiguedad docente</div><div class='uri-valor'><%=@adminnomina.antiguedad_docente%></div><br />
    <div class='uri-titulo'>Antiguedad administrativa</div><div class='uri-valor'><%=@adminnomina.antiguedad_administrativo%></div><br />
    <div class='uri-titulo'>Número matriculación</div><div class='uri-valor'><%=@adminnomina.numero_matriculacion %></div><br />
    
  </div>
 
 
 <!--  begin detalles    -->

  <!--<div class="uri-data-right"> 
  	
 
    <h4>Detalle de la asignación</h4>
    
    <table class="table table-striped table-bordered table-hover">
    	
      
	        <th>nn</th>
        <th style="text-align:right;">nn</th>

      </tr>

        <tr>

         
          <td></td>
      
          <td style="text-align:right;"></td>
		         
        </tr>
        
        <tr>

         
          <td>    </td>
      
          <td style="text-align:right;"></td>
		     
        </tr>
        
        <tr>
        	<td></td>
      
          <td style="text-align:right;"></td>
        	
        </tr>
        
        <tr>
        	<td></td>
      
          <td style="text-align:right;"></td>
        	
        </tr>
        <tr>
        	<td></td>
      
          <td style="text-align:right;"></td>
        	
        </tr>
        
        <tr>
        	<td></td>
      
          <td style="text-align:right;"></td>
        	
        </tr>
         <tr>
        	<th>nn</th>
      
          <td style="text-align:right;"></td>
        	
        </tr>

    </table>
	
    
    

</div>-->
 <!--  end detalles    -->

  <div style="clear:both;"></div>
  <div class="uri-data-fin">

    <br />
    <%= image_tag "datos-abiertos-nuevo.png", :style => "width:240px; margin-bottom:10px;" %>
    <a href="http://www.w3.org/TR/microdata/"><%= image_tag "microdata-icon.png", :style => "width:32px; margin-bottom:10px;" %></a>
    </br>
    <span>Descargar Administrativo:</span>
	<% image_star = image_tag('star.png', :style => 'width:12px;padding-bottom:10px;') %>
    <% if params[:codigo_trabajador].present? %>
    	<% ruta = mec_custom_url(id_nomimas_docentes_url(params[:codigo_trabajador], format: 'json'))%>
    <% else %>
      <% ruta = mec_custom_url(id_nominas_docentes_url(params[:codigo_trabajador], format: 'json'))%>
    <% end %>
    <%= link_to "JSON#{image_star * 3}".html_safe, ruta, :target => "_target", :style => "margin-left:10px;", :class => 'icon icon-page_white_text_width'%>

    <%# image_star = image_tag('star.png', :style => 'width:12px;padding-bottom:10px;') %>
    <%# if params[:institucion] && params[:institucion][:anio].present? %>
      <%# ruta = mec_custom_url(id_instituciones_url(params[:codigo_institucion], periodo: { anio: params[:institucion][:anio]}, format: 'json'))%>
    <%# else %>
      <%# ruta = mec_custom_url(id_instituciones_url(params[:codigo_institucion], format: 'json'))%>
    <%# end %>
    <%#= link_to "JSON#{image_star * 3}".html_safe, ruta, :target => "_target", :style => "margin-left:10px;", :class => 'icon icon-page_white_text_width'%>

  </div>

 <% else %>

  <div>No se ha encontrado el administrativo</div>

<% end %>
 

<style>

  h2 {border-bottom: 3px solid gray;}
  h4 {border-bottom: 1px dashed silver;}
  div.uri-data-filter { width:100%; border-bottom: 4px solid silver;margin-top:30px;padding-bottom:10px;}
  div.uri-data-left { width:45%; float:left;}
  div.uri-data-right { width:52%; float:right; border-left: 4px solid silver; padding-left:20px;}
  div.uri-data-fin { width:100%; border-top: 4px solid silver;margin-bottom:30px;clear:both;margin-top:20px;}
  div.uri-data-left br {clear:both;}
  div.uri-titulo, div.uri-valor { font-size: 12px; float:left; padding:5px; height:40px;}
  div.uri-titulo { border-bottom: 1px solid silver;width:30%; border-left:6px solid silver; background-color: #efefef; color: #5a86a5;}
  div.uri-valor { border-bottom: 1px solid silver;border-right: 1px solid silver; width:70%; -moz-box-shadow: 9px -4px 11px #878787;}

  div.first{
    border-top:solid 1px silver;
    -moz-border-radius-topleft: 0px;
    -moz-border-radius-topright:21px;
    -moz-border-radius-bottomleft:0px;
    -moz-border-radius-bottomright:0px;
    -webkit-border-top-left-radius:0px;
    -webkit-border-top-right-radius:21px;
    -webkit-border-bottom-left-radius:0px;
    -webkit-border-bottom-right-radius:0px;
    border-top-left-radius:0px;
    border-top-right-radius:21px;
    border-bottom-left-radius:0px;
    border-bottom-right-radius:0px;
  }

  div.last{
    border-bottom:solid 1px silver;
    -moz-border-radius-topleft: 0px;
    -moz-border-radius-topright:0px;
    -moz-border-radius-bottomleft:0px;
    -moz-border-radius-bottomright:21px;
    -webkit-border-top-left-radius:0px;
    -webkit-border-top-right-radius:0px;
    -webkit-border-bottom-left-radius:0px;
    -webkit-border-bottom-right-radius:21px;
    border-top-left-radius:0px;
    border-top-right-radius:0px;
    border-bottom-left-radius:0px;
    border-bottom-right-radius:21px;
  } 

</style>

app/views/nominas/detalles.js.erb
$("#nominas-detalles-<%= @nomina.first.id_trabajador %>-<%= @nomina.first.id_objeto_gasto%>").html("<%= escape_javascript( render :partial => 'detalles') %>");

app/views/nominas/docentes_lista.js.erb
$("#nominas-lista").html("<%= escape_javascript(render :partial => "docentes_lista", :locals => { :nomina => @nomina }) %>");

app/views/nominas/lista.js.erb
$("#nominas-lista").html("<%= escape_javascript(render :partial => "lista", :locals => { :nomina => @nomina }) %>");